# Generated by Django 6.1 on 2026-08-19 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0002_patients_appointments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointments',
            new_name='Appointment',
        ),
        migrations.RenameModel(
            old_name='Doctors',
            new_name='Doctor',
        ),
        migrations.RenameModel(
            old_name='Patients',
            new_name='Patient',
        ),
    ]
